# Setup
setup: multi_task
fp16: True
aux_loss: False

# Database
train_db_name: NYUD
val_db_name: NYUD 
trBatch: 6
valBatch: 6
nworkers: 6

# Optimizer and scheduler
epochs: 300
optimizer: adam
optimizer_kwargs:
   lr: 0.001
   weight_decay: 0.0001
scheduler: poly

# Model
model: groupnet
model_kwargs:
   tam: False
   num_tasks: 2
   num_shared: 2
backbone: groupnet
backbone_kwargs:
   channels: 32
   depths: [8, 8, 8]
   channel_shuffle: [True, True, True]
   dilated: False
head: deeplab

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True
   # include_edge: True
   # include_normals: True
   # edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_scheme: baseline
   loss_weights:
       semseg: 1.0
       depth: 1.0
      #  normals: 10
      #  edge: 50.0

eval_final_10_epochs_only: False
eval_freq: 10
