# Setup
setup: multi_task
fp16: True
aux_loss: False

# Database
train_db_name: PASCALContext
val_db_name: PASCALContext
trBatch: 6
valBatch: 6
nworkers: 6

# Optimizer and scheduler
epochs: 300
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
scheduler: poly

# Model
model: groupnet
model_kwargs:
   num_tasks: 4
   num_shared: 1
backbone: groupnet
backbone_kwargs:
   channels: 32
   depths: [2, 2, 2]
   channel_shuffle: [True, True, False]
   dilated: False
head: deeplab

# Tasks
task_dictionary:
   include_semseg: True
   include_human_parts: True
   include_sal: True
   # include_edge: True
   include_normals: True
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_scheme: baseline
   loss_weights:
       semseg: 1.0
       human_parts: 2.0
       sal: 5.0
      #  edge: 50.0
       normals: 10.0

eval_final_10_epochs_only: True