# Setup
setup: single_task

# Database
train_db_name: PASCALContext
val_db_name: PASCALContext
trBatch: 12
valBatch: 12
nworkers: 4

# Optimizer and scheduler
epochs: 60
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
scheduler: poly

# Model
model: baseline
model_kwargs:
   channels: 32
   num_tasks: 4
   num_shared: 1
backbone: resnet18
backbone_kwargs:
   pretrained: True
   dilated: True
head: deeplab

# Tasks
task_dictionary:
   include_edge: True
   edge_w: 0.95
