# Setup
setup: multi_task

# Database
train_db_name: NYUD
val_db_name: NYUD
trBatch: 6
valBatch: 6
nworkers: 4

# Optimizer and scheduler
epochs: 300
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
scheduler: poly

# Model
model: baseline
backbone: resnet18
backbone_kwargs:
   pretrained: False
   dilated: True
head: deeplab

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True

# Loss kwargs
loss_kwargs:
   loss_scheme: baseline
   loss_weights:
       semseg: 1.0
       depth: 1.0