# Setup
setup: multi_task
fp16: True
aux_loss: False

# Database
train_db_name: NYUD
val_db_name: NYUD
trBatch: 6
valBatch: 6
nworkers: 8  # 4 * num_GPUs

# Optimizer and scheduler
epochs: 300
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
scheduler: poly

# Model
model: squadnet
model_kwargs:
   num_tasks: 2
   num_shared: 2
backbone: squadnet
backbone_kwargs:
   channels: 32
   depths: [8, 8, 8]
   channel_shuffle: [True, True, False]
   dilated: False
head: deeplab

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True

# Loss kwargs
loss_kwargs:
   loss_scheme: baseline
   loss_weights:
       semseg: 1.0
       depth: 1.0